/*
 * This source file was generated by the Gradle 'init' task
 */
package io.sqlnotebook;

import io.sqlnotebook.config.ConfigParser;
import io.sqlnotebook.config.ConnectionConfig;
import io.sqlnotebook.connection.ConnectionRegistry;
import io.sqlnotebook.duckdb.DuckDbRegistrar;
import io.sqlnotebook.duckdb.FileSourceRegistry;
import io.sqlnotebook.duckdb.PinnedViewRegistry;
import io.sqlnotebook.executor.QueryExecutor;
import io.sqlnotebook.server.HttpServer;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.File;
import java.io.IOException;
import java.nio.file.*;
import java.util.Collections;
import java.util.Map;

/**
 * Application entry point.
 *
 * Startup sequence:
 *   1. Parse sql.properties → ConnectionRegistry (persistent JDBC connections)
 *   2. Build DuckDbRegistrar (creates ~/.sqlnotebook/duckdb/ and uploads/ dirs)
 *   3. Build FileSourceRegistry → rehydrate sources.json (re-registers all
 *      file and remote data sources from the previous session)
 *   4. Start HttpServer on localhost:4000
 *   5. Register JVM shutdown hook to cleanly close all pools
 *
 * sql.properties is optional — the app starts fine with no JDBC connections
 * configured (the user can add them at runtime via /connections/add).
 */
public class App {

    private static final Logger log = LoggerFactory.getLogger(App.class);

    private static final int    DEFAULT_PORT   = 8080;
    private static final String CONFIG_FILE    = "sql.properties";

    public static void main(String[] args) throws Exception {
        // --clean wipes duckdb/ and uploads/ dev leftovers then exits
        if (args.length > 0 && args[0].equals("--clean")) {
            clean();
            return;
        }

        int port = parsePort(args);

        // Step 1 — Persistant JDBC connection
        Map<String, ConnectionConfig> configs = loadConfigs();
        ConnectionRegistry registry = new  ConnectionRegistry(configs);
        log.info("[startup] loaded {} persistant connection(s)", configs.size());

        // Step 2 — DuckDB registrar
        DuckDbRegistrar duckDbRegistrar = new DuckDbRegistrar(registry);
        log.info("[startup] DuckDB registrar loaded");

        // Step 3 — File Source registry
        FileSourceRegistry sourceRegistry = new FileSourceRegistry(duckDbRegistrar);
        sourceRegistry.rehydrate();
        log.info("[startup] file source registry ready ({} source(s) rehydrated)", sourceRegistry.list().size());

        // Step 4 — Pinned view registry (disk-backed DuckDB datasets from federated results)
        PinnedViewRegistry pinnedRegistry = new PinnedViewRegistry(registry);
        log.info("[startup] pinned view registry ready ({} pinned dataset(s))", pinnedRegistry.listPinned().size());

        // Step 5 — Warm up all pools (validates connections, marks unhealthy ones)
        Map<String, String> warmUpResults = registry.warmUp();
        long healthy   = warmUpResults.values().stream().filter(String::isEmpty).count();
        long unhealthy = warmUpResults.size() - healthy;
        log.info("[startup] pool warm-up complete — {}/{} healthy", healthy, warmUpResults.size());
        if (unhealthy > 0) log.warn("[startup] {} pool(s) failed warm-up — check credentials/connectivity", unhealthy);

        // Step 6 — Http server
        QueryExecutor executor = new QueryExecutor(registry);
        HttpServer server = new HttpServer(port, registry, executor, sourceRegistry, duckDbRegistrar, pinnedRegistry, (int) healthy);
        server.start();
        log.info("[startup] server listening on http://127.0.0.1:{}", server.getPort());

        // Step 6 — Shutdown hook
        Runtime.getRuntime().addShutdownHook(new Thread(() -> {
            log.info("[shutdown] stopping server...");
            try { server.stop(); } catch (Exception e) {
                log.warn("[shutdown] error stopping server: {}", e.getMessage());
            }
            registry.shutdown();
            log.info("[shutdown] server stopped");
        }, "shutdown-hook"));

        server.join();
    }

    /**
     * Wipes accumulated dev/test files from ~/.sqlnotebook/duckdb/ and
     * ~/.sqlnotebook/uploads/. Drafts and backups are left untouched.
     * Invoked when the first CLI arg is {@code --clean}.
     */
    private static void clean() throws IOException {
        Path home = Path.of(System.getProperty("user.home")).resolve(".sqlnotebook");
        Path duckdbDir   = home.resolve("duckdb");
        Path uploadsDir  = home.resolve("uploads");
        Path pinnedDir   = home.resolve("pinned");
        Path sourcesJson = home.resolve("sources.json");
        Path sourcesTmp  = home.resolve("sources.json.tmp");

        long dbFiles  = deleteContents(duckdbDir);
        long uploaded = deleteContents(uploadsDir);
        long pinned   = deleteContents(pinnedDir);

        // Remove sources.json so stale file-source entries don't block re-registration
        boolean sourcesDeleted = Files.deleteIfExists(sourcesJson);
        Files.deleteIfExists(sourcesTmp);

        log.info("[clean] deleted {} file(s) from {}", dbFiles,  duckdbDir);
        log.info("[clean] deleted {} file(s) from {}", uploaded, uploadsDir);
        log.info("[clean] deleted {} file(s) from {}", pinned,   pinnedDir);
        if (sourcesDeleted) log.info("[clean] deleted sources.json");
        log.info("[clean] done — restart the app normally to begin fresh");
    }

    /**
     * Deletes all regular files directly inside {@code dir} (non-recursive).
     * Directories inside are left intact. Returns the count of deleted files.
     */
    private static long deleteContents(Path dir) throws IOException {
        if (!Files.exists(dir)) return 0;
        try (var stream = Files.walk(dir, 1)) {
            return stream
                    .filter(p -> !p.equals(dir))
                    .filter(Files::isRegularFile)
                    .peek(p -> {
                        try { Files.delete(p); }
                        catch (IOException e) {
                            log.warn("[clean] could not delete {}: {}", p, e.getMessage());
                        }
                    })
                    .count();
        }
    }

    /**
     * Parse sql.properties if it exists — silently returns empty map if absent.
     * The app is fully functional without any pre-configured JDBC connections.
     */
    private static Map<String, ConnectionConfig> loadConfigs() {
        File propsFile = new File(CONFIG_FILE);
        if (!propsFile.exists()) {
            log.info("[startup] no sql.properties found — starting with no persistent connections");
            return Collections.emptyMap();
        }
        try {
            return new ConfigParser().parse(CONFIG_FILE);
        } catch (Exception e) {
            log.warn("[startup] failed to parse sql.properties: {} — starting with no connections",
                    e.getMessage());
            return Collections.emptyMap();
        }
    }

    /**
     * Allow port override via first CLI arg: java -jar app.jar port_num
     * Falls back to DEFAULT_PORT (8080) if absent or invalid.
     */
    private static int parsePort(String[] args) {
        if (args.length > 0) {
            try {
                int port = Integer.parseInt(args[0]);
                if (port > 0 && port < 65536) return port;
            } catch (NumberFormatException ignored) {}
        }
        return DEFAULT_PORT;
    }
}
